[metadata]
creation_date = "2021/08/23"
maturity = "development"
updated_date = "2021/08/23"

[rule]
author = ["John Torakis"]
description = """
This rule identifies network traffic where the host sent more than 20*524288 Bytes (~10Mib) to a host that does not belong to the Internal Network. All Private Addresses are filtered out.
The rule is based on raw flow size, so it is not bound to a Protocol, such as TCP or UDP.
"""
language = "kuery"
name = "Data Leakage Detection"
risk_score = 47
rule_id = "7f80a667-5ac5-430d-8395-c5de457b46ea"
severity = "medium"
type = "threshold"
license = "Skroutz SIEM License"
tags = ["Network", "Elastic", "Exfiltration","Threat Detection"]
index = ["packetbeat-*"]


query = '''
destination.bytes > 524288 and
  not destination.ip:(
    10.0.0.0/8 or
    127.0.0.0/8 or
    169.254.0.0/16 or
    172.16.0.0/12 or
    192.0.0.0/24 or
    192.0.0.0/29 or
    192.0.0.8/32 or
    192.0.0.9/32 or
    192.0.0.10/32 or
    192.0.0.170/32 or
    192.0.0.171/32 or
    192.0.2.0/24 or
    192.31.196.0/24 or
    192.52.193.0/24 or
    192.168.0.0/16 or
    192.88.99.0/24 or
    224.0.0.0/4 or
    100.64.0.0/10 or
    192.175.48.0/24 or
    198.18.0.0/15 or
    198.51.100.0/24 or
    203.0.113.0/24 or
    240.0.0.0/4 or
    "::1" or
    "FE80::/10" or
    "FF00::/8"
  )
'''

[rule.threshold]
value = 25
field = ["source.ip","destination.ip"]

[[rule.threat]]
framework = "MITRE ATT&CK"

[[rule.threat.technique]]
id = "T1041"
name = "Exfiltration Over C2 Channel"
reference = "https://attack.mitre.org/techniques/T1041/"

[rule.threat.tactic]
id = "TA0010"
name = "Exfiltration"
reference = "https://attack.mitre.org/tactics/TA0010/"

